CREATE TABLE IF NOT EXISTS catalog_risk_management.agent_risk_assessment (
  agent_name string,
  agent_risk_assessment_name string,
  analysis_requested_at timestamp,
  assessor string,
  audit string,
  autonomy_of_action_rationale string,
  bias_classification_rationale string,
  comments string,
  contextual_awareness_rationale string,
  dynamic_identity_rationale string,
  dynamic_tool_use_rationale string,
  eu_ai_act_article_5_prohibited_ai_practices_evaluation string,
  eu_ai_act_article_6_high_risk_ai_systems_evaluation string,
  goal_driven_planning_rationale string,
  memory_use_rationale string,
  multi_agent_interactions_rationale string,
  non_determinism_rationale string,
  opacity_reflexivity_rationale string,
  payment_card_industry string,
  personally_identifiable_information string,
  protected_health_information string,
  risk_classification string,
  risk_classification_analyzed timestamp,
  risk_classification_rationale string,
  self_modification_rationale string,
  state string,
  summary string,
  type_of_risk string,
  updated_ts timestamp,
  created_ts timestamp,
  created_by string,
  updated_by string,
  assessment_id string,
  agent_id string,
  aars_score decimal(10, 2),
  ai_vulnerability_scoring_system_aivss_weighting decimal(10, 2),
  aivss_score decimal(10, 2),
  autonomy_of_action decimal(10, 2),
  bias_risk decimal(10, 2),
  contextual_awareness decimal(10, 2),
  cvss_score decimal(10, 2),
  dynamic_identity decimal(10, 2),
  dynamic_tool_use decimal(10, 2),
  goal_driven_planning decimal(10, 2),
  memory_use decimal(10, 2),
  multi_agent_interactions decimal(10, 2),
  non_determinism decimal(10, 2),
  regulatory_risk_weighting decimal(10, 2),
  risk_classification_score decimal(10, 2),
  self_modification decimal(10, 2),
  opacity_reflexivity decimal(10, 2),
  blended_risk_score decimal(10, 2),
  agent_internal_id string)
PARTITIONED BY (day(`created_ts`))
LOCATION 's3://{{S3_BUCKET}}/iceberg/risk_management/agent_risk_assessment'
TBLPROPERTIES (
  'table_type'='iceberg',
  'write_compression'='snappy',
  'format'='parquet'
);
